export const WORD_LISTS: Record<string, string[]> = {
  animals: [
    "dog",
    "cat",
    "elephant",
    "giraffe",
    "penguin",
    "dolphin",
    "butterfly",
    "kangaroo",
    "octopus",
    "hamster",
    "parrot",
    "turtle",
    "rabbit",
    "koala",
    "panda",
    "flamingo",
    "cheetah",
    "seahorse",
    "gorilla",
    "hedgehog",
  ],
  foods: [
    "pizza",
    "banana",
    "chocolate",
    "hamburger",
    "strawberry",
    "pancake",
    "sandwich",
    "spaghetti",
    "pineapple",
    "blueberry",
    "cupcake",
    "popcorn",
    "pretzel",
    "waffle",
    "avocado",
    "broccoli",
    "cinnamon",
    "coconut",
    "muffin",
    "noodles",
  ],
  sports: [
    "soccer",
    "basketball",
    "swimming",
    "tennis",
    "baseball",
    "volleyball",
    "gymnastics",
    "skateboarding",
    "badminton",
    "hockey",
    "surfing",
    "bowling",
    "karate",
    "cycling",
    "archery",
  ],
  nature: [
    "rainbow",
    "mountain",
    "ocean",
    "sunflower",
    "volcano",
    "waterfall",
    "thunder",
    "glacier",
    "meadow",
    "forest",
    "desert",
    "island",
    "canyon",
    "tornado",
    "blossom",
  ],
  colors: [
    "purple",
    "orange",
    "turquoise",
    "magenta",
    "crimson",
    "indigo",
    "scarlet",
    "violet",
    "emerald",
    "golden",
  ],
};

export function getRandomWord(): { word: string; category: string } {
  const categories = Object.keys(WORD_LISTS);
  const category = categories[Math.floor(Math.random() * categories.length)];
  const words = WORD_LISTS[category];
  const word = words[Math.floor(Math.random() * words.length)];
  return { word, category };
}
